version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: ^22.14.00
    commands:
      - echo "Instalando dependencias..."
      - npm install
  build:
    commands:
      - echo "Aplicación construida correctamente"

artifacts:
  files:
    - '**/*'
